  version: '3.7'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=contentsearch
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
    web:
      build: .
      container_name: content-search
      volumes:
        - .:/app
        - /app/node_modules 
      ports:
        - "3000:3000"
      depends_on:
        - db